version: "3.7"

services:
  mssqldb:
    container_name: mssqldb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PIPasswordStrong123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - mssqldb_data:/var/opt/mssql

volumes:
  mssqldb_data:
